import Head from "next/head";
import Content from "../components/content/";
import Footer from "../components/Footer";
import Map from "../components/Map";
import Model from "../components/Model";
import References from "../components/References";
import styles from "../styles/Home.module.scss";
import Header from "./../components/header/index";

export default function Home() {
  return (
    <div>
      <Head>
        /logo.png
        <title>KG Teknoloji - Anasayfa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header position={true} />
      <main className={styles.main}>
        <Content show={true} />
        <Model />
        <References />
      </main>
      <Map />
      <Footer />
    </div>
  );
}
